on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  TEST_TAG: corefiling/pdf2html:test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: ./src/Pdf2Html
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Set up Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.x"
      - name: E2E tests
        run: |
          docker run --rm --detach -p 8080:8080 --name pdf2html ${{ env.TEST_TAG }}
          dotnet test
          docker stop pdf2html
